### ISSUE TITLE
WTF is this!??

### ISSUE THREAD

**Issue by piwawa** [arthur-qiu/ReliTalk#6]
```
ReliTalk) root@vultr:~/AIGC/ReliTalk/code# python scripts/exp_runner.py --conf ./confs/IMavatar_supervised_Obama.conf
wandb: WARNING Path ../data/experiments/wandb/ wasn't writable, using system temp directory
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: WARNING Path ../data/experiments/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path ../data/experiments/wandb/ wasn't writable, using system temp directory
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: WARNING Path ../data/experiments/wandb/ wasn't writable, using system temp directory
shell command : scripts/exp_runner.py --conf ./confs/IMavatar_supervised_Obama.conf
Loading data ...
Traceback (most recent call last):
  File "scripts/exp_runner.py", line 36, in <module>
    wandb_workspace=opt.wandb_workspace,
  File "../code/scripts/train.py", line 95, in __init__
    **self.conf.get_config('dataset.train'))
  File "../code/datasets/real_dataset.py", line 76, in __init__
    assert os.path.exists(instance_dir), "Data directory is empty"
AssertionError: Data directory is empty

wandb: Waiting for W&B process to finish, PID 49696... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync ../data/experiments/wandb/offline-run-20231203_112609-2khyrnup
wandb: Find logs at: ../data/experiments/wandb/offline-run-20231203_112609-2khyrnup/logs/debug.log
wandb: 
```

And why it asks me to create an account? I just need to train model locally.

![image](https://github.com/arthur-qiu/ReliTalk/assets/46926496/9d87a072-404b-445f-be43-8eb04e86f924)

![image](https://github.com/arthur-qiu/ReliTalk/assets/46926496/208cf5d0-0ab8-4285-bbc1-335ed37f09f3)

**Comment by arthur-qiu** [comment]
Hi, wandb is inherited from IMavatar. If you don't want to use it, delete "wandb" related code in https://github.com/arthur-qiu/ReliTalk/blob/main/code/scripts/train.py and https://github.com/arthur-qiu/ReliTalk/blob/main/code/scripts/train_relight.py.
